### ISSUE TITLE
"assigns" being called on TestResponse subject

### ISSUE THREAD

**Issue by fionawhim** [sj26/rspec-rails-assign#2]
I'm trying out rspec-rails-assign with Rails 3.2 and RSpec 2.13. However, following the pattern in the README.md leads to an error:

> Failure/Error: it { should assign(:install_url => nil) }
>   NoMethodError:
>      undefined method `assigns' for #ActionController::TestResponse:0x007fce85653140

This is with the example's:

`subject { get :show }`

In reading the code, it seems that the matcher is calling `assigns` on the subject, which may be a response, whereas it needs to be called on the `ExampleGroup` (`@scope` in this case) in order to line up with the ActionPack implementation.

Am I missing something basic? Or maybe dependencies have changed since this was written?

**Comment by sj26** [comment]
Sorry for the late response.

To be honest, I haven't used this library in a long time. Feel free to dig a little deeper if you wish, but I'd recommend just using the built in rails assigns accessor.
